spring.application.name=student_management
spring.datasource.url=jdbc:mysql://localhost:3306/studentdb
spring.datasource.username=root
spring.datasource.password=Muthu@2007
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true